/*
 * kcg_sensors_global.h
 *
 *  Created on: 7 sep 2025
 *      Author: lukas
 */

#ifndef SOURCE_EMBEDDED_USER_MACROS_GLOBAL_H
#define SOURCE_EMBEDDED_USER_MACROS_GLOBAL_H
/*generated by SCADE Code Generator*/
#ifndef kcg_assume
#define kcg_assume(x)
#endif

#ifndef kcg_guarantee
#define kcg_guarantee(x)
#endif

#endif /*SOURCE_EMBEDDED_USER_MACROS_H_GLOBAL*/
